### 회원가입기능
POST http://localhost:3000/auth/register
Content-Type: application/json

{ 
  "email" : "thddbxor01@naver.com",
  "nickname" : "방구대장",
  "password" : "dbxor1401!"
}


### 로그인기능
POST http://localhost:3000/auth/login
Content-Type: application/json

{ 
  "email" : "thddbxor02@naver.com", 
  "password" : "dbxor1401!"
}

### 로그아웃기능
POST http://localhost:3000/auth/logout
Content-Type: application/json 


